package com.berg.orbis;

import com.berg.orbis.biome.BiomeClassifier;
import com.berg.orbis.biome.RealWorldBiomeSource;
import com.berg.orbis.command.TeleportCommands;
import com.berg.orbis.config.OrbisConfig;
import com.berg.orbis.config.WorldSettings;
import com.berg.orbis.dem.BicubicElevationSampler;
import com.berg.orbis.dem.BlendedElevationService;
import com.berg.orbis.dem.DemSource;
import com.berg.orbis.dem.DemTileProvider;
import com.berg.orbis.dem.GlobalDemSource;
import com.berg.orbis.dem.ImageServiceDemSource;
import com.berg.orbis.dem.VerticalMapping;
import com.berg.orbis.imagery.ImageryProvider;
import com.berg.orbis.landmark.LandmarkRegistry;
import com.berg.orbis.osm.CoordinateMapper;
import com.berg.orbis.osm.FeatureRasterizer;
import com.berg.orbis.osm.OsmDataProvider;
import com.berg.orbis.osm.OsmRegionManager;
import com.berg.orbis.worldgen.RealWorldChunkGenerator;
import com.berg.orbis.worldgen.WorldModel;
import net.fabricmc.api.ModInitializer;
import net.fabricmc.fabric.api.event.lifecycle.v1.ServerLifecycleEvents;
import net.fabricmc.fabric.api.event.lifecycle.v1.ServerTickEvents;
import net.fabricmc.loader.api.FabricLoader;
import net.minecraft.server.level.ServerPlayer;
import net.minecraft.world.level.Level;

import java.io.IOException;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;

/**
 * Entry point. Owns the installation config (config/orbisterrarum/orbisterrarum.json)
 * and the active {@link WorldModel}: projection, elevation, OSM streaming,
 * climate, landmarks and painters for one set of {@link WorldSettings}. A
 * world carries its settings inside its generator; when a world with
 * different settings is opened the model is rebuilt for it.
 */
public class OrbisMod implements ModInitializer {

    private static Path configDir;
    private static volatile OrbisConfig config;
    private static volatile WorldModel model;
    private static volatile WorldSettings modelSettings;
    /** [lowest Y, highest Y] of the running world when it is a cubic one (Cubic Chunks), else null; see {@link #useCubicHeights}. */
    private static volatile int[] cubicHeights;
    private static volatile int[] modelCubicHeights;
    /** True while the server shuts down: nothing may wait for downloads then. */
    private static volatile boolean stopping;

    /**
     * True when this server's chunk writes should skip the per-chunk sync: an Orbis world and the "Fast chunk
     * writes" setting on. Asked by Minecraft while it creates each level (see mixin ServerLevelWritesMixin).
     */
    public static boolean fastChunkWrites(net.minecraft.server.MinecraftServer server) {
        OrbisConfig c = config;
        return c != null && c.fastChunkWrites && isOrbisWorld(server);
    }

    /** True when the server's overworld is generated by Orbis Terrarum. */
    public static boolean isOrbisWorld(net.minecraft.server.MinecraftServer server) {
        try {
            net.minecraft.world.level.dimension.LevelStem stem = server.registryAccess().lookupOrThrow(net.minecraft.core.registries.Registries.LEVEL_STEM)
                    .getValue(net.minecraft.world.level.dimension.LevelStem.OVERWORLD);
            return stem != null && stem.generator() instanceof RealWorldChunkGenerator;
        } catch (RuntimeException e) {
            return false;
        }
    }

    public static boolean stopping() {
        return stopping;
    }

    /** The world height the active model was built for. */
    private static int modelHeight;
    /** The height of the level actually loaded (from its dimension type), 0 while no level is loaded. */
    private static volatile int levelHeight;
    private static volatile Float cloudHeight;
    private static Thread spawnPrefetch;
    /** The model built while the mod starts (the defaults'): a client fetches nothing for it. */
    private static boolean startupModel;

    /** Cloud layer Y for the active world (about 800 m above the ground at its origin), or null before a model exists. */
    public static Float cloudHeightOverride() {
        return cloudHeight;
    }

    /** The active world model (never null after initialisation). */
    /** Starts a sweep over the chunks an operator selected on the world map, and tells them how it went. */
    private static void pregenSelection(net.minecraft.server.level.ServerPlayer player, com.berg.orbis.net.PregenSelectionPayload payload) {
        net.minecraft.commands.CommandSourceStack source = player.createCommandSourceStack();
        if (!net.minecraft.commands.Commands.hasPermission(net.minecraft.commands.Commands.LEVEL_GAMEMASTERS).test(source)) {
            player.sendSystemMessage(net.minecraft.network.chat.Component.literal("Only operators can pre-generate."));
            return;
        }
        net.minecraft.server.level.ServerLevel level = player.level().getServer().overworld();
        if (!(level.getChunkSource().getGenerator() instanceof com.berg.orbis.worldgen.RealWorldChunkGenerator)) {
            player.sendSystemMessage(net.minecraft.network.chat.Component.literal("This world is not an Orbis Terrarum world."));
            return;
        }
        com.berg.orbis.worldgen.ChunkSelection selection = com.berg.orbis.worldgen.ChunkSelection.of(payload.shapes());
        System.out.println(String.format(java.util.Locale.ROOT, "[orbis] %s asked to pre-generate a map selection: %d shapes, %,d chunks",
                player.getName().getString(), payload.shapes().size(), selection.count()));
        player.sendSystemMessage(com.berg.orbis.worldgen.PregenTask.startSelection(level, selection, payload.skipSea()));
    }

    public static WorldModel model() {
        return model;
    }

    /** The installation config; world settings live in it as the defaults for new worlds. */
    public static OrbisConfig config() {
        return config;
    }

    /**
     * True when the level is an Orbis Terrarum world: its generator is Orbis's. (Its sea level alone does not say: a cubic Orbis world has
     * its sea at Y 0, as the End has.)
     */
    public static boolean isOrbisLevel(net.minecraft.world.level.Level level) {
        return level instanceof net.minecraft.server.level.ServerLevel server
                && server.getChunkSource().getGenerator() instanceof com.berg.orbis.worldgen.RealWorldChunkGenerator;
    }

    /**
     * True when a level with this sea level may be an Orbis Terrarum world, where nothing but the sea level is known (no vanilla dimension
     * has one near -1700; a cubic Orbis world's is 0, as the End's is): prefer {@link #isOrbisLevel}.
     */
    public static boolean isOrbisSeaLevel(int seaLevel) {
        WorldModel m = model;
        return m != null && seaLevel == m.cfg().seaLevelY;
    }

    public static Path configDir() {
        return configDir;
    }

    /** Where downloads and imported data are kept: the data folder setting, else the config folder. */
    public static Path dataDir() {
        return dataDirFor(config);
    }

    private static final java.util.Set<String> DATA_FOLDER_NOTES = java.util.concurrent.ConcurrentHashMap.newKeySet();
    /** The folders of downloads and imports the mod keeps (everything but the config file, landmarks, schematics, marks). */
    private static final String[] DATA_SUBFOLDERS = {"dem-cache", "dem-hires-cache", "dsm-cache", "imagery-cache",
            "osm-cache", "extracts", "places", "heights", "worldcover-cache", "canopy-cache", "canopy-src", "geology-cache",
            "lake-survey-cache", "lake-depths", "lake-depths-src", "nvdb-cache", "map-tile-cache", "mc-map-cache", "outline-cache", "preview",
            "usgs-cache"};

    /** How a move of the downloads went: files moved, bytes moved, files skipped (already there), files that failed. */
    public record MoveResult(long files, long bytes, long skipped, long failed) {}

    /**
     * Moves every download and import folder from one data folder to another, file by file (a copy and a delete
     * between drives, a rename on the same drive), keeping a file the target already has. Empty folders left behind
     * are removed. Run it while no world is open: the mod reads these files while it generates.
     */
    /** How much there is to move: {files, bytes} in the download folders of a data folder. */
    public static long[] countData(Path from) throws IOException {
        long[] n = new long[2];
        for (String sub : DATA_SUBFOLDERS) {
            Path src = from.resolve(sub);
            if (!java.nio.file.Files.isDirectory(src)) continue;
            java.nio.file.Files.walkFileTree(src, new java.nio.file.SimpleFileVisitor<>() {
                @Override
                public java.nio.file.FileVisitResult visitFile(Path file, java.nio.file.attribute.BasicFileAttributes attrs) {
                    n[0]++;
                    n[1] += attrs.size();
                    return java.nio.file.FileVisitResult.CONTINUE;
                }
            });
        }
        return n;
    }

    /**
     * As {@link #moveData(Path, Path, java.util.function.BiConsumer)}, reporting {files done, bytes done} about four times
     * a second (files done counts the ones skipped or failed too, so it reaches the total).
     */
    public static MoveResult moveData(Path from, Path to, java.util.function.BiConsumer<Long, Long> progress) throws IOException {
        long[] n = new long[4]; // files, bytes, skipped, failed
        long[] lastReport = {System.currentTimeMillis()};
        java.nio.file.Files.createDirectories(to);
        for (String sub : DATA_SUBFOLDERS) {
            Path src = from.resolve(sub);
            if (!java.nio.file.Files.isDirectory(src)) continue;
            Path dst = to.resolve(sub);
            java.nio.file.Files.walkFileTree(src, new java.nio.file.SimpleFileVisitor<>() {
                @Override
                public java.nio.file.FileVisitResult visitFile(Path file, java.nio.file.attribute.BasicFileAttributes attrs) {
                    Path target = dst.resolve(src.relativize(file).toString());
                    try {
                        java.nio.file.Files.createDirectories(target.getParent());
                        if (java.nio.file.Files.exists(target) && java.nio.file.Files.size(target) == attrs.size()) {
                            java.nio.file.Files.delete(file); // same file already there (a half-copied one is replaced below)
                            n[2]++;
                        } else {
                            java.nio.file.Files.move(file, target, java.nio.file.StandardCopyOption.REPLACE_EXISTING);
                            n[0]++;
                            n[1] += attrs.size();
                        }
                    } catch (IOException e) {
                        n[3]++;
                    }
                    if (progress != null && System.currentTimeMillis() - lastReport[0] > 250) {
                        lastReport[0] = System.currentTimeMillis();
                        progress.accept(n[0] + n[2] + n[3], n[1] + 0L);
                    }
                    return java.nio.file.FileVisitResult.CONTINUE;
                }

                @Override
                public java.nio.file.FileVisitResult postVisitDirectory(Path dir, IOException e) {
                    try (var left = java.nio.file.Files.list(dir)) {
                        if (left.findAny().isEmpty()) java.nio.file.Files.delete(dir);
                    } catch (IOException ignored) {
                    }
                    return java.nio.file.FileVisitResult.CONTINUE;
                }
            });
        }
        return new MoveResult(n[0], n[1], n[2], n[3]);
    }

    /** The data folder a config asks for (created if needed), or the config folder when it is empty or unusable. */
    public static Path dataDirFor(OrbisConfig c) {
        String f = c == null || c.dataFolder == null ? "" : c.dataFolder.trim();
        if (f.isEmpty()) return configDir;
        Path p;
        try {
            if (f.startsWith("~")) f = System.getProperty("user.home") + f.substring(1);
            p = Path.of(f);
            if (!p.isAbsolute()) p = FabricLoader.getInstance().getGameDir().resolve(p);
            p = p.normalize();
            java.nio.file.Files.createDirectories(p);
        } catch (IOException | RuntimeException e) {
            if (DATA_FOLDER_NOTES.add("bad:" + f)) {
                System.err.println("[orbis] Data folder '" + f + "' cannot be used (" + e + "); keeping downloads in " + configDir);
            }
            return configDir;
        }
        if (DATA_FOLDER_NOTES.add("use:" + p)) {
            System.out.println("[orbis] Downloads and imported data are kept in " + p);
            // Nothing is moved (it can be gigabytes, across drives): say what to move to keep it.
            List<String> left = new ArrayList<>();
            for (String sub : DATA_SUBFOLDERS) {
                if (configDir != null && java.nio.file.Files.isDirectory(configDir.resolve(sub)) && !java.nio.file.Files.exists(p.resolve(sub))) left.add(sub);
            }
            if (!left.isEmpty()) {
                System.out.println("[orbis] Still in " + configDir + " (move them to " + p + " to keep using them, else they are downloaded again): "
                        + String.join(", ", left));
            }
        }
        return p;
    }

    public static WorldSettings defaultWorldSettings() {
        return WorldSettings.fromConfig(config);
    }

    /** The model for these settings, rebuilding (and retiring the previous one) if they differ from the active model's. */
    public static synchronized WorldModel modelFor(WorldSettings settings) {
        if (settings == null) settings = defaultWorldSettings();
        WorldModel current = model;
        int[] cubic = cubicHeights;
        int height = cubic != null ? cubic[1] - cubic[0] + 1 : effectiveHeight(settings);
        if (current != null && settings.equals(modelSettings) && height == modelHeight && cubic == modelCubicHeights) return current;
        System.out.println("[orbis] Building world model: " + settings.describe() + " (world height " + height + ")");
        OrbisConfig effective = settings.effective(config);
        effective.worldHeight = height;
        if (cubic != null) {
            // A cubic world (Cubic Chunks): it holds the real heights, so a block is a metre up and down from sea level at
            // Y 0, with nothing squeezed.
            effective.minY = cubic[0];
            effective.seaLevelY = 0;
            effective.verticalMode = "clamp";
            System.out.println("[orbis] Cubic world: Y " + cubic[0] + ".." + cubic[1] + ", sea level Y 0, 1 block = 1 m up and down");
        }
        WorldModel built = buildModel(effective, configDir);
        model = built;
        modelSettings = settings.copy();
        modelHeight = height;
        modelCubicHeights = cubic;
        cloudHeight = (float) built.cloudHeightY();
        System.out.println("[orbis] Cloud layer at Y " + cloudHeight);
        if (current != null) current.shutdown();
        boolean client = FabricLoader.getInstance().getEnvironmentType() == net.fabricmc.api.EnvType.CLIENT;
        if (built.regions() != null && config.prefetchSpawnAtStartup && !(startupModel && client)) {
            // Start downloading the spawn regions NOW, while the player is
            // still in the menu: vanilla's spawn search generates chunks
            // synchronously on the server thread and would otherwise look
            // frozen at "Create New World" until the downloads finish.
            spawnPrefetch = new Thread(built.regions()::prefetchSpawnArea, "Orbis-spawn-prefetch");
            spawnPrefetch.setDaemon(true);
            spawnPrefetch.start();
        }
        return built;
    }

    /**
     * Switches the model to a cubic world's (Cubic Chunks; called as the world's cube generator is made): its own lowest and
     * highest Y instead of the dimension's, sea level at Y 0 and a block a metre up and down. Until the server stops.
     */
    public static synchronized WorldModel useCubicHeights(WorldSettings settings, int minY, int maxY) {
        int[] current = cubicHeights;
        if (current == null || current[0] != minY || current[1] != maxY) cubicHeights = new int[]{minY, maxY};
        return modelFor(settings);
    }

    /** True while the running world is a cubic one (Cubic Chunks). */
    public static boolean cubicWorld() {
        return cubicHeights != null;
    }

    /**
     * The height the model for these settings must use: the loaded level's own (a world's height is fixed by
     * its dimension type), else the settings' value, else the full dimension.
     */
    private static int effectiveHeight(WorldSettings settings) {
        int loaded = levelHeight;
        if (loaded > 0) return loaded;
        return settings.worldHeight > 0 ? com.berg.orbis.worldgen.WorldHeight.snap(settings.worldHeight) : OrbisConfig.DIMENSION_HEIGHT;
    }

    /** Stores world settings as the defaults for new worlds and switches the active model to them. */
    public static synchronized void saveWorldDefaults(WorldSettings settings) {
        int height = settings.worldHeight, softCeiling = config.softCeilingBlocks;
        settings.applyTo(config);
        // applyTo gives a world's own model its height (0 becomes the full 4064); as a default for the next world,
        // 0 has to stay 0 (fitted to that world). Every Done in Customize used to switch the fitted height off for
        // good. A world's own squeeze range (fitted worlds) is not a default either.
        config.worldHeight = Math.max(0, height);
        config.softCeilingBlocks = softCeiling;
        // Nor is a world's selected area: the next world starts from what is drawn on its own generator map.
        config.pregenShapes = new java.util.ArrayList<>();
        config.pregenSelectionSkipsSea = false;
        config.sanitizeValues();
        saveConfigFile();
        modelFor(settings);
    }

    /** Changes an installation setting that needs no model rebuild (a client preference) and saves the config. */
    public static synchronized void updateConfig(java.util.function.Consumer<OrbisConfig> change) {
        change.accept(config);
        config.sanitizeValues();
        saveConfigFile();
    }

    /** Replaces the installation config (from the settings screen), saves it and rebuilds the model. */
    public static synchronized void replaceConfig(OrbisConfig newConfig) {
        newConfig.sanitizeValues();
        config = newConfig;
        saveConfigFile();
        modelSettings = null; // network / data-source settings changed: force a rebuild
        modelFor(WorldSettings.fromConfig(config));
    }

    /** The mod used to be called TellusPlus: carry its config folder (and the valuable caches inside) over once. */
    private static void migrateFromTellusPlus(java.nio.file.Path configRoot) {
        java.nio.file.Path old = configRoot.resolve("tellusplus");
        try {
            if (java.nio.file.Files.isDirectory(old) && !java.nio.file.Files.exists(configDir)) {
                java.nio.file.Files.move(old, configDir);
                java.nio.file.Path oldJson = configDir.resolve("tellusplus.json");
                if (java.nio.file.Files.exists(oldJson)) java.nio.file.Files.move(oldJson, configDir.resolve("orbisterrarum.json"));
                System.out.println("[orbis] Migrated config/tellusplus to config/orbisterrarum (caches kept)");
            }
        } catch (IOException e) {
            System.err.println("[orbis] Could not migrate the old TellusPlus config folder: " + e);
        }
    }

    private static void saveConfigFile() {
        try {
            config.save(configDir.resolve("orbisterrarum.json"));
        } catch (IOException e) {
            System.err.println("[orbis] Could not save config: " + e);
        }
    }

    @Override
    public void onInitialize() {
        configDir = FabricLoader.getInstance().getConfigDir().resolve("orbisterrarum");
        migrateFromTellusPlus(FabricLoader.getInstance().getConfigDir());
        config = OrbisConfig.load(configDir.resolve("orbisterrarum.json"));

        RealWorldChunkGenerator.register();
        com.berg.orbis.worldgen.BackgroundLocate.register();
        // The world map's data: where this world sits on Earth, for players who have the mod (vanilla players
        // never get it, so they still join with plain Minecraft).
        net.fabricmc.fabric.api.networking.v1.PayloadTypeRegistry.clientboundPlay()
                .register(com.berg.orbis.net.WorldInfoPayload.TYPE, com.berg.orbis.net.WorldInfoPayload.CODEC);
        net.fabricmc.fabric.api.networking.v1.PayloadTypeRegistry.clientboundPlay()
                .register(com.berg.orbis.net.AllowedAreaPayload.TYPE, com.berg.orbis.net.AllowedAreaPayload.CODEC);
        com.berg.orbis.map.BlockMapService.register();
        com.berg.orbis.compat.dh.DhCompat.init(); // optional: only acts when Distant Horizons is installed
        com.berg.orbis.mc.Cubic.init(); // optional: cubic worlds, when Cubic Chunks is installed (26.3)
        net.fabricmc.fabric.api.networking.v1.ServerPlayConnectionEvents.JOIN.register((handler, sender, server) -> {
            WorldModel m = model;
            if (m == null || !(server.overworld().getChunkSource().getGenerator() instanceof RealWorldChunkGenerator)) return;
            if (!net.fabricmc.fabric.api.networking.v1.ServerPlayNetworking.canSend(handler.getPlayer(), com.berg.orbis.net.WorldInfoPayload.TYPE)) return;
            OrbisConfig c = m.cfg();
            net.fabricmc.fabric.api.networking.v1.ServerPlayNetworking.send(handler.getPlayer(),
                    new com.berg.orbis.net.WorldInfoPayload(c.originLat, c.originLon, c.metersPerBlock, c.projection,
                            com.berg.orbis.map.BlockMapService.worldId(server)));
            com.berg.orbis.worldgen.HardLimit.sendTo(handler.getPlayer());
        });
        RealWorldBiomeSource.register();
        TeleportCommands.register();
        com.berg.orbis.sky.RealSky.register();

        // The defaults' model: on a dedicated server it is the world's, so its spawn area is fetched now; a client does
        // not know yet which world it will open (one it creates or opens builds its own model), so it fetches nothing.
        startupModel = true;
        try {
            modelFor(defaultWorldSettings());
        } finally {
            startupModel = false;
        }
        if (FabricLoader.getInstance().getEnvironmentType() == net.fabricmc.api.EnvType.SERVER) {
            // A dedicated server creates its world itself: give it the height pack before it does.
            com.berg.orbis.worldgen.WorldHeight.prepareDedicatedServer(FabricLoader.getInstance().getGameDir(), config, model);
        }

        // One advancement per real landmark, as a world datapack written on the first start.
        ServerLifecycleEvents.SERVER_STARTED.register(server -> {
            if (isOrbisWorld(server)) {
                // The server thread first when every core is busy: it runs part of every chunk's generation (and the
                // unloads), and during a pre-generation the workers, map regions being prepared and the renderer
                // otherwise left it two thirds of a core (a flight recording on a 6-core laptop at 98% CPU). This
                // runs on the server thread, which lives as long as this world.
                Thread.currentThread().setPriority(Thread.MAX_PRIORITY);
            }
            try {
                com.berg.orbis.worldgen.Landmarks.ensure(server);
            } catch (RuntimeException e) {
                System.err.println("[orbis] Landmark datapack: " + e);
            }
            try {
                com.berg.orbis.worldgen.WorldSpawn.applyOnce(server);
            } catch (RuntimeException e) {
                System.err.println("[orbis] Spawn point: " + e);
            }
        });
        ServerLifecycleEvents.SERVER_STARTING.register(server -> {
            if (fastChunkWrites(server)) System.out.println("[orbis] Chunk writes: not forced to disk one by one in this Orbis world (setting \"Fast chunk writes\")");
            net.minecraft.world.level.dimension.LevelStem stem = server.registryAccess().lookupOrThrow(net.minecraft.core.registries.Registries.LEVEL_STEM)
                    .getValue(net.minecraft.world.level.dimension.LevelStem.OVERWORLD);
            if (stem == null || !(stem.generator() instanceof RealWorldChunkGenerator)) {
                System.out.println("[orbis] Not an Orbis Terrarum world; the mod stays out of it");
                return;
            }
            // The level's dimension type is the truth about its height; the model must agree with it.
            int actual = server.registryAccess().lookupOrThrow(net.minecraft.core.registries.Registries.DIMENSION_TYPE)
                    .getOrThrow(net.minecraft.world.level.dimension.BuiltinDimensionTypes.OVERWORLD).value().height();
            levelHeight = actual;
            WorldModel m = model;
            if (m != null && m.cfg().worldHeight != actual && !cubicWorld()) {
                System.out.println("[orbis] Level height is " + actual + " (model had " + m.cfg().worldHeight + "); rebuilding the model");
                m = modelFor(modelSettings);
            }
            System.out.println("[orbis] World Y " + OrbisConfig.DIMENSION_MIN_Y + ".." + (OrbisConfig.DIMENSION_MIN_Y + actual - 1) + " (" + actual / 16 + " sections)");
            if (m != null && m.regions() != null) {
                System.out.println("[orbis] Server starting; " + m.regions().stats());
            }
        });
        ServerLifecycleEvents.SERVER_STOPPED.register(server -> {
            levelHeight = 0;
            cubicHeights = null;
        });
        ServerLifecycleEvents.SERVER_STARTING.register(server -> stopping = false);
        ServerLifecycleEvents.SERVER_STOPPING.register(server -> {
            stopping = true;
            com.berg.orbis.worldgen.PregenTask.serverStopping();
        });
        com.berg.orbis.worldgen.AutoPregen.register();
        com.berg.orbis.worldgen.HardLimit.register();
        // A selection drawn on the world map (operators only, like /orbis pregen).
        net.fabricmc.fabric.api.networking.v1.PayloadTypeRegistry.serverboundPlay()
                .register(com.berg.orbis.net.PregenSelectionPayload.TYPE, com.berg.orbis.net.PregenSelectionPayload.CODEC);
        net.fabricmc.fabric.api.networking.v1.ServerPlayNetworking.registerGlobalReceiver(com.berg.orbis.net.PregenSelectionPayload.TYPE,
                (payload, ctx) -> ctx.server().execute(() -> pregenSelection(ctx.player(), payload)));
        // Display frames furnished before they were generated locked: lock them as they load.
        net.fabricmc.fabric.api.event.lifecycle.v1.ServerEntityEvents.ENTITY_LOAD.register((entity, level) -> {
            if (entity instanceof net.minecraft.world.entity.decoration.ItemFrame frame && model != null
                    && level.getChunkSource().getGenerator() instanceof com.berg.orbis.worldgen.RealWorldChunkGenerator) {
                com.berg.orbis.render.Interiors.lockOldDisplay(frame, model, level.getServer());
            }
        });
        // Every 2 s, keep the regions around and ahead of each player
        // downloading so exploration never waits on Overpass.
        int[] tick = {0};
        ServerTickEvents.END_SERVER_TICK.register(server -> {
            com.berg.orbis.worldgen.Landmarks.tick(server);
            com.berg.orbis.export.AternosExport.tick(server);
            if (++tick[0] % 40 != 0) return;
            WorldModel m = model;
            if (m == null || m.regions() == null) return;
            // Only in an Orbis world: the model of the installation's place exists in any world, and an Aternos
            // export opened in singleplayer (a plain world) had Bergen's map regions loaded around the player.
            net.minecraft.server.level.ServerLevel overworld = server.overworld();
            if (overworld == null || !(overworld.getChunkSource().getGenerator() instanceof RealWorldChunkGenerator)) return;
            List<int[]> positions = new ArrayList<>();
            for (ServerPlayer p : server.getPlayerList().getPlayers()) {
                if (p.level().dimension() != Level.OVERWORLD) continue;
                positions.add(new int[]{(int) Math.floor(p.getX()), (int) Math.floor(p.getZ())});
            }
            if (!positions.isEmpty()) m.regions().updatePlayers(positions);
        });
        ServerTickEvents.END_SERVER_TICK.register(com.berg.orbis.worldgen.PregenTask::tick);

        System.out.println("[orbis] Origin " + config.originLat + ", " + config.originLon + " at 1 block = " + config.metersPerBlock
                + " m; sea level Y=" + config.seaLevelY + "; world Y " + config.minY + ".." + config.maxY());
    }

    // ------------------------------------------------------------------ model construction

    private static WorldModel buildModel(OrbisConfig cfg, Path cfgDir) {
        // Downloads and imports live in the data folder (the config folder unless one is set); landmarks and
        // schematics stay with the config.
        Path data = dataDirFor(cfg);
        if (data == null) data = cfgDir;
        // ---- elevation ----
        DemTileProvider tiles = new DemTileProvider(data.resolve("dem-cache"), cfg.demTileUrl, cfg.demTileCacheSize);
        System.out.println("[orbis] Terrain tiles (zoom " + cfg.demZoom + "): " + tiles.describeSource());
        if (cfg.bareEarthTerrain && cfg.demZoom >= 13 && cfg.demTileUrl != null && cfg.demTileUrl.contains("mapterhorn")) {
            // Copernicus measures treetops and roofs; where no survey exists the ground comes from GEDTM30 instead.
            tiles.setCorrection(cfg.demZoom, new com.berg.orbis.dem.BareEarthBlend(tiles, new com.berg.orbis.dem.BareEarth(data.resolve("dem-cache").resolve("gedtm30"))));
            System.out.println("[orbis] Where no national survey exists: " + com.berg.orbis.dem.BareEarth.ATTRIBUTION
                    + ", blended into the surveys over " + (int) com.berg.orbis.dem.BareEarthBlend.BLEND_METRES + " m");
        }
        BicubicElevationSampler globalSampler = new BicubicElevationSampler(tiles, cfg.demZoom);
        List<DemSource> sources = new ArrayList<>();
        // Lidar is only worth its downloads at fine scales (whatever the switches say): see OrbisConfig.lidarUseful.
        boolean lidar = OrbisConfig.lidarUseful(cfg.metersPerBlock);
        if (!lidar && (cfg.useHighResElevation || cfg.lidarSurfaceModel)) {
            System.out.println("[orbis] Lidar terrain and surface model skipped at 1 block = " + cfg.metersPerBlock
                    + " m (they only help up to " + (int) OrbisConfig.LIDAR_MAX_METERS_PER_BLOCK + " m per block)");
        }
        if (cfg.useHighResElevation && lidar) {
            for (OrbisConfig.ElevationSource es : cfg.elevationSources) {
                if (es != null && es.enabled && es.urlTemplate != null && !es.urlTemplate.isBlank()) {
                    sources.add(new ImageServiceDemSource(es, data.resolve("dem-hires-cache")));
                }
            }
        }
        sources.add(new GlobalDemSource(globalSampler));
        BlendedElevationService elevation = new BlendedElevationService(sources);
        if (cfg.useBathymetry && cfg.generateWater) {
            DemTileProvider seaTiles = new DemTileProvider(data.resolve("dem-cache"), cfg.bathymetryTileUrl, 128);
            // Seascape has regional detail to zoom 14 and global coverage below; missing zooms fall back to the parent tile.
            elevation.setBathymetry(new GlobalDemSource(new BicubicElevationSampler(seaTiles, Math.min(cfg.demZoom, 14))), cfg.maxSeaDepthMeters);
            System.out.println("[orbis] Sea floor: " + seaTiles.describeSource() + " (floor drawn down to " + (int) cfg.maxSeaDepthMeters + " m)");
        }

        // Surface model (tops of buildings/trees) -- only where a source covers the point, no global fallback.
        List<DemSource> surfaceSources = new ArrayList<>();
        // Each service where it covers (its country), Kartverket's only with its switch on (it needs a VPN outside Norway).
        if (lidar && cfg.buildingHeightsFromSurfaceModel) {
            for (OrbisConfig.ElevationSource es : cfg.surfaceModelSources) {
                if (es == null || !es.enabled) continue;
                // Kartverket's: always with its switch on, else by itself while it answers from this network (new
                // worlds; worlds made before 1.1.1 keep their heights from the other sources).
                boolean auto = es.needsSwitch && !(cfg.useHighResElevation || cfg.lidarSurfaceModel);
                if (auto && !cfg.kartverketWhenReachable) continue;
                if (es.stacSearch != null && !es.stacSearch.isBlank()) {
                    // Files in a national grid, read block by block.
                    if (com.berg.orbis.dem.NationalGrids.knows(es.crs)) surfaceSources.add(new com.berg.orbis.dem.CogDemSource(es, data.resolve("dsm-cache")));
                    continue;
                }
                if (es.urlTemplate == null || es.urlTemplate.isBlank()) continue;
                ImageServiceDemSource s = new ImageServiceDemSource(es, data.resolve("dsm-cache"));
                if (auto) s.useWhenReachable(com.berg.orbis.config.DataSources.KARTVERKET_PROBE);
                if (es.aboveGround) s.setGround(elevation::sampleMeters); // heights above the ground: on the terrain
                surfaceSources.add(s);
            }
        }

        // ---- aerial imagery ----
        ImageryProvider imagery = cfg.useAerialImagery ? new ImageryProvider(cfg, data.resolve("imagery-cache")) : null;
        if (imagery != null && imagery.isEnabled()) {
            System.out.println("[orbis] Aerial imagery enabled (zoom " + imagery.zoom() + "). " + imagery.attribution());
        }

        // ---- projection / climate / landmarks ----
        CoordinateMapper mapper = new CoordinateMapper(cfg.originLat, cfg.originLon, cfg.metersPerBlock,
                CoordinateMapper.Projection.of(cfg.projection));
        VerticalMapping vertical = new VerticalMapping(cfg, mapper, tiles);
        System.out.println("[orbis] Vertical mapping: " + vertical.mode() + (cfg.heightSquash > 1 ? String.format(java.util.Locale.ROOT,
                ", uniform heights: 1 block up = %.2f m", cfg.verticalMetersPerBlock()) : "") + " (1:1 below " + cfg.reliefKneeMeters
                + " m, sea level Y=" + cfg.seaLevelY + ", ceiling Y=" + cfg.maxY() + ")");
        BiomeClassifier classifier = new BiomeClassifier(cfg);
        LandmarkRegistry landmarks = LandmarkRegistry.load(cfgDir.resolve("landmarks.json"), cfgDir.resolve("schematics"), mapper);

        // ---- OSM streaming ----
        OsmRegionManager regions = null;
        com.berg.orbis.landcover.WorldCoverProvider worldCover = null;
        boolean anyOsm = cfg.generateBuildings || cfg.generateRoads || cfg.generateWater || cfg.generateLandCover
                || cfg.generateTrees || cfg.generateStreetFurniture;
        if (anyOsm) {
            OsmDataProvider osm = new OsmDataProvider(data.resolve("osm-cache"), cfg.overpassUrls, cfg.overpassTimeoutSeconds,
                    cfg.overpassConcurrentRequests, cfg.overpassRetries);
            // Imported country extracts (config/orbisterrarum/extracts/<name>/) are used before Overpass.
            osm.setLocalExtracts(com.berg.orbis.osm.extract.LocalExtractStore.get(data.resolve("extracts")), cfg.metersPerBlock);
            // Points of interest imported from Overture Places (config/orbisterrarum/places/) join OSM's.
            if (cfg.externalPlaces) osm.setPlaces(com.berg.orbis.osm.PlacesStore.get(data.resolve("places")));
            // Both lambdas answer in block Y through the shared vertical mapping,
            // so bridge decks, water surfaces and building bases sit on the terrain.
            FeatureRasterizer.Elevation elevationInBlocks = (bx, bz) -> {
                try {
                    double[] ll = mapper.toLatLon(bx, bz);
                    double e = elevation.sampleMeters(ll[0], ll[1]);
                    return Double.isNaN(e) ? Double.NaN : vertical.toY(e, bx, bz);
                } catch (RuntimeException ex) {
                    return Double.NaN;
                }
            };
            FeatureRasterizer.Elevation surfaceInBlocks = surfaceSources.isEmpty() ? null : (bx, bz) -> {
                try {
                    double[] ll = mapper.toLatLon(bx, bz);
                    for (DemSource s : surfaceSources) {
                        if (!s.hasCoverage(ll[0], ll[1])) continue;
                        double v = s.sampleMeters(ll[0], ll[1]);
                        if (!Double.isNaN(v)) return vertical.toY(v, bx, bz);
                    }
                    return Double.NaN;
                } catch (RuntimeException ex) {
                    return Double.NaN;
                }
            };
            FeatureRasterizer rasterizer = new FeatureRasterizer(mapper, cfg, elevationInBlocks, surfaceInBlocks, imagery, landmarks);
            // Real heights for what depends on them (the block heights are bent in high mountains by the relief mode).
            rasterizer.setElevationMeters((bx, bz) -> {
                try {
                    double[] ll = mapper.toLatLon(bx, bz);
                    return elevation.sampleMeters(ll[0], ll[1]);
                } catch (RuntimeException ex) {
                    return Double.NaN;
                }
            });
            // The terrain tiles under a region, all at once, before its roads and water read them point by point.
            rasterizer.setTerrainPrefetch(box -> tiles.prefetch(cfg.demZoom, box[0], box[1], box[2], box[3]));
            // The surface model's tiles under a region's buildings, fetched in parallel before the buildings are measured.
            if (!surfaceSources.isEmpty()) {
                rasterizer.setSurfacePrefetch(boxes -> {
                    for (DemSource s : surfaceSources) s.prefetch(boxes);
                });
            }
            // Tunnel ends near a region edge: the ways around that node, from the same source as the region data.
            rasterizer.setWayLookup((lat, lon, radiusM) -> {
                double dLat = radiusM / 111_320.0, dLon = radiusM / (111_320.0 * Math.cos(Math.toRadians(lat)));
                try {
                    return osm.getData(lat - dLat, lon - dLon, lat + dLat, lon + dLon);
                } catch (Exception e) {
                    return null;
                }
            });
            if (cfg.generateBuildings && cfg.buildingSources != null && !cfg.buildingSources.isEmpty()) {
                com.berg.orbis.osm.BuildingDatabases dbs = new com.berg.orbis.osm.BuildingDatabases(cfg, data.resolve("building-db-cache"));
                if (!dbs.isEmpty()) rasterizer.setBuildingDatabases(dbs);
            }
            if (cfg.generateBuildings && cfg.atlasBuildingHeights) {
                com.berg.orbis.osm.HeightStore hs = com.berg.orbis.osm.HeightStore.get(data.resolve("heights"));
                rasterizer.setHeights(hs);
                if (!hs.isEmpty()) System.out.println("[orbis] Building heights found in heights/: GlobalBuildingAtlas (TUM, CC BY-NC 4.0) fills in untagged buildings");
            }
            if (cfg.generateLandCover && cfg.worldCoverLandCover) {
                worldCover = new com.berg.orbis.landcover.WorldCoverProvider(data.resolve("worldcover-cache"), cfg.worldCoverUrl);
                rasterizer.setWorldCover(worldCover);
                System.out.println("[orbis] Land cover gaps are filled from " + com.berg.orbis.landcover.WorldCoverProvider.ATTRIBUTION);
            }
            // Tree canopy height in blocks: lidar surface minus terrain where a surface model covers, else the
            // imported global canopy map, else unknown (random trees as before).
            if (cfg.treesFromCanopy && cfg.generateTrees) {
                com.berg.orbis.dem.CanopyProvider canopyMap = com.berg.orbis.dem.CanopyProvider.open(data.resolve("canopy-cache"));
                if (canopyMap != null) System.out.println("[orbis] Canopy height tiles found in canopy-cache: trees follow the canopy map");
                if (!surfaceSources.isEmpty()) {
                    // Where the canopy map does not cover a region, its trees are read off the surface model column by
                    // column: the region's tiles first, all at once (one at a time as columns asked for them took a
                    // minute a region in the Netherlands).
                    rasterizer.setCanopyPrefetch(box -> {
                        if (canopyMap != null && !Double.isNaN(canopyMap.sampleMeters((box[0] + box[2]) / 2, (box[1] + box[3]) / 2))) return;
                        for (DemSource s : surfaceSources) s.prefetch(List.of(box));
                    });
                }
                if (!surfaceSources.isEmpty() || canopyMap != null) {
                    rasterizer.setCanopy((bx, bz) -> {
                        try {
                            double[] ll = mapper.toLatLon(bx, bz);
                            // The canopy map first: the surface model would be downloaded over every forest for it.
                            if (canopyMap != null) {
                                double c = canopyMap.sampleMeters(ll[0], ll[1]);
                                if (!Double.isNaN(c)) return c / cfg.metersPerBlock;
                            }
                            for (DemSource s : surfaceSources) {
                                if (!s.hasCoverage(ll[0], ll[1])) continue;
                                double dsm = s.sampleMeters(ll[0], ll[1]);
                                if (Double.isNaN(dsm)) continue;
                                double dtm = elevation.sampleMeters(ll[0], ll[1]);
                                if (!Double.isNaN(dtm)) return Math.max(0, dsm - dtm) / cfg.metersPerBlock;
                            }
                            return Double.NaN;
                        } catch (RuntimeException ex) {
                            return Double.NaN;
                        }
                    });
                }
            }
            // Surveyed road widths and lanes from the Norwegian road database, where OSM has none.
            // Lake and river beds: NVE's surveyed lakes (Norway), GLOBathy greatest depths where imported, the shoreline.
            if (cfg.realWaterDepths && cfg.generateWater) {
                com.berg.orbis.water.NveLakes nve = cfg.nveLakeServiceUrl == null || cfg.nveLakeServiceUrl.isBlank() ? null
                        : new com.berg.orbis.water.NveLakes(data.resolve("lake-survey-cache"), cfg.nveLakeServiceUrl);
                com.berg.orbis.water.GlobalLakeDepths global = com.berg.orbis.water.GlobalLakeDepths.open(data.resolve("lake-depths"));
                if (global != null) System.out.println("[orbis] Lake depths found in lake-depths/: GLOBathy greatest depths for " + global.size() + " lakes (CC0)");
                com.berg.orbis.water.LakeSurveys surveys = cfg.lakeSurveySources == null || cfg.lakeSurveySources.isEmpty() ? null
                        : new com.berg.orbis.water.LakeSurveys(cfg, data.resolve("lake-depth-cache"));
                rasterizer.setWaterBeds(new com.berg.orbis.water.WaterBeds(mapper, cfg.metersPerBlock, nve, global)
                        .withSurveys(surveys == null || surveys.isEmpty() ? null : surveys));
            }
            // The rock under each place: NGU's bedrock map in Norway, Macrostrat's world map everywhere else (and
            // where NGU has nothing). Each keeps its downloads in a folder of its own.
            if (cfg.bedrockTypes) {
                java.util.List<com.berg.orbis.geology.Rocks.Source> maps = new java.util.ArrayList<>();
                if (cfg.bedrockServiceUrl != null && !cfg.bedrockServiceUrl.isBlank()) {
                    maps.add(new com.berg.orbis.geology.BedrockMap(data.resolve("geology-cache"), cfg.bedrockServiceUrl));
                }
                if (cfg.worldGeologyUrl != null && !cfg.worldGeologyUrl.isBlank()) {
                    maps.add(new com.berg.orbis.geology.MacrostratMap(data.resolve("geology-macrostrat-cache"), cfg.worldGeologyUrl));
                }
                if (!maps.isEmpty()) rasterizer.setBedrock(new com.berg.orbis.geology.Rocks(maps));
            }
            if (cfg.nvdbRoadWidths) rasterizer.setNvdb(new com.berg.orbis.osm.NvdbRoads.Store(data.resolve("nvdb-cache")));
            if (cfg.nvdbRoadWidths && cfg.roadSources != null && !cfg.roadSources.isEmpty()) {
                com.berg.orbis.osm.RoadDatabases roads = new com.berg.orbis.osm.RoadDatabases(cfg, data.resolve("road-db-cache"));
                if (!roads.isEmpty()) rasterizer.setRoadDatabases(roads);
            }
            regions = new OsmRegionManager(cfg, mapper, osm, rasterizer);
        }

        WorldModel model = new WorldModel(cfg, mapper, elevation, vertical, classifier, regions, landmarks);
        if (cfg.realSnow) model.setSnowCover(com.berg.orbis.sky.SnowCover.shared(data.resolve("snow-cache")));
        model.setCoarseSampler(new BicubicElevationSampler(tiles, Math.min(cfg.demZoom, 11)));
        model.setTerrainTiles(tiles, cfg.demZoom);
        model.setWorldCover(worldCover);
        if (regions != null) regions.setTerrainFailures(tiles::failures);
        return model;
    }
}
